### ISSUE TITLE
binding ReactiveProperty<string> in TextBox and inputting Korean character, there is an issue

### ISSUE THREAD

**Issue by unoyu** [runceel/ReactiveProperty#61] opened 2018-01-12 07:43 UTC
I'm looking over and testing to decided to use your great solution in my work. 
But, I found out an issue.

Binding ReactiveProperty<string> in a TextBox for WPF and input **Korean characters**, there are some issues.

1. After writing an Korean character, the cursor goes to begging of the TextBox.
2. If one character is written in the TextBox, next input character is ignored. It is repeated continuosly. 
2. Input Korean charters continuously, the results are reversed.

The result of issues is below.

![input issue](https://user-images.githubusercontent.com/25603074/34864277-d8315f36-f7b6-11e7-9af6-bbcf9c3fbb56.PNG)

Code snippet is below.

`<TextBox Text="{Binding KoreanMessage.Value, UpdateSourceTrigger=PropertyChanged}" />`

I hope this issue will be fixed soon.
I really thank you for your passion on **ReactiveProperty**

**Comment by runceel** [comment] 2018-01-12 12:34
Thank you for reporting an issue.

Does this issue occured the case of using ReactiveProperty?
I think that this issue will occur the case of POCO properties too.

If that is incorrect. then could you tell me that how to type Korean characters using keyboard(I'm using US layout keyboard.).
I can setup the Korean language pack, but I don't know how to input it.

**Comment by unoyu** [comment] 2018-01-12 13:00
Thank you replay for my reporting.

Bindings from POCO properties works fine. This issue is occured when using ReactiveProperty.

To input Korean, you are supposed to change IME settiing(**2 Beolsik** ). 
![korean-microsoft-ime-2-beolsik](https://user-images.githubusercontent.com/25603074/34876047-3c3a2f18-f7e3-11e7-8298-ac0e407f6c3f.jpg)

This site has a well organized information for that. Have a look.
https://lovingkorean.com/2016/01/13/how-to-change-keyboard-language-in-windows-10-to-korean/

If you have any further question, please let me know. 
Thank you.

**Comment by runceel** [comment] 2018-01-14 10:27
Thank you for explanation for install steps.
I could re-present the issue. The cause is it which ReactiveProperty auto dispatch to UI thread.
The code is following:
https://github.com/runceel/ReactiveProperty/blob/master/Source/ReactiveProperty.NETStandard/ReactiveProperty.cs#L309

This feature can be disabled following steps:

- add App class's Startup event handler
- Write a below code

```cs
ReactivePropertyScheduler.SetDefault(ImmediateScheduler.Instance);
```

Could you check previous steps?

**Comment by unoyu** [comment] 2018-01-14 14:52
Great! It works find!! Thank you for your support.
Again, your ReactiveProperty solution very simple and nice!!

**Comment by runceel** [comment] 2018-01-15 00:27
Thank you so much.

This solution has a large impact.
ReactivePropertyScheduler.SetDefault method change the all ReactiveProperty's classes scheduler.

For example, ReactiveCollection's CollectionChanged event and ReadOnlyReactiveCollection's CollectionChanged event.

If this behavior is an issue, then you should set the scheduler per instance creation time.

```cs
new ReactiveProperty<string>(raiseEventScheduler: ImmediateScheduler.Instance);
```

**Comment by runceel** [comment] 2018-01-15 12:51
I'll close this issue. If you have an another issue, then create a new issue or re-open this issue.
Thank you!

**Closed by runceel** 2018-01-15 12:51 UTC

**Comment by unoyu** [comment] 2018-01-15 13:37
Thank you for your kind help!
